version: '3.7'

services:
  sisdash_front:
    container_name: sisdash_front
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CI=true

  nginx:
    container_name: nginx
    image: nginx:1.25.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - sisdash_front 