version: '3.7'

services:
  sisdash_front:
    container_name: sisdash_front
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CI=true
    networks:
      - sisdash_network

#   nginx:
#     container_name: nginx
#     image: nginx:latest
#     restart: always
#     volumes:
#       - './log/:/var/log/nginx/'
#     ports:
#       - '80:80'
#     networks:
#       - sisdash_network

networks:
  sisdash_network:
    driver: bridge